### ISSUE TITLE
Feature request: snooze for a period of time

### ISSUE THREAD

**Issue by rattrayalex** [tobiasdalhof/sanersocialmedia#25]
With News Feed Eradicator, when I go to disable a site, it asks if I want to disable the news feed eradicator for a period of time rather than forever:

<img width="870" alt="Screenshot 2023-04-23 at 8 31 51 PM" src="https://user-images.githubusercontent.com/704302/233875727-11402ef2-01f1-4703-85ef-1cde15ab1b89.png">

I find this fantastic – often, at a certain point in the day, I treat myself to 5min of HN browsing (or whatever) and don't get in the habit of leaving it stuck in the "on" position. I find this to be a better "escape hatch" than switching to incognito as well.

I know it might be a little more involved to build, and sadly I'm not in a position to be able to offer to contribute right now. 

Thoughts?

**Comment by tobiasdalhof** [comment]
Thank you for your feature request. I appreciate your feedback and suggestions for improving the Saner Social Media extension.

I agree that the ability to temporarily disable the extension for a set amount of time rather than permanently would be useful. To achieve this, I could potentially add a "snooze" feature that allows users to turn off the extension for a set amount of time across all sites.

While adding a snooze option for each individual site might be excessive, I am open to feedback on this and welcome further discussion on the best way to implement this feature in a user-friendly way.

**Comment by rattrayalex** [comment]
I think a global snooze would be just fine if you were doing it for 5 or 10 minutes, but if for some reason you want to  turn on only, say, Reddit for an hour or a day or something, it might be a little dangerous to have that "leak" into also seeing news feeds on other sites, which may be more addicting.

**Comment by raoulritter** [comment]
I also think this would be very beneficial. I love the work you've done but think it would be more useful to have it with a snooze feature. I sometimes want to check a site for 5-10 minutes. It would nice to also be nudged away after that time frame.

**Comment by tobiasdalhof** [comment]
BlockSite has a cool focus mode, and I'm thinking we could create something similar. It's like the reverse of a focus mode 😄

![chrome_9HaIkAQ9ct](https://github.com/tobiasdalhof/sanersocialmedia/assets/10046578/82b65369-fa1b-427c-a991-4a6e609562fc)

**Comment by tobiasdalhof** [comment]
I've started working on snooze mode, what do you think? @raoulritter @rattrayalex 


https://github.com/tobiasdalhof/sanersocialmedia/assets/10046578/97475909-5ffa-49ae-9f80-43b90880531e

**Comment by raoulritter** [comment]
@tobiasdalhof Looks amazing!

**Comment by tobiasdalhof** [comment]
Snooze mode is now available in `v1.9.0`. Please open a issue if you have feedback and suggestions. Thanks!

**Comment by rattrayalex** [comment]
Nice, love it!! Thanks for this @tobiasdalhof !
