### ISSUE TITLE
Add support for Instagram reels

### ISSUE THREAD

**Issue by raoulritter** [tobiasdalhof/sanersocialmedia#26]
Hi @tobiasdalhof ,

Thanks for the fantastic work you've done on this program. I would love to have it also block Instagram reels, perhaps in the same technique used for Youtube Shorts. Thanks in advance. 

Kind Regards,

Raoul

**Comment by tobiasdalhof** [comment]
Thank you for your suggestion. We can certainly explore adding support to block Instagram reels. Additionally, considering your request, we can also consider blocking the explore feed. Integration should be straightforward and feasible.

**Comment by tobiasdalhof** [comment]
Also, blocking the home feed seems to be broken?

![image](https://github.com/tobiasdalhof/sanersocialmedia/assets/10046578/d05107d9-e653-41e1-93ba-04181797f701)

**Comment by raoulritter** [comment]
Hi @tobiasdalhof,

For me, it appears to be working on the home screen. However, not in the reels page. If you give me a few pointers to the technique used, I will try to make a PR for the fix in the next few weeks. I appreciate any help you can provide. 


<img width="1890" alt="image" src="https://github.com/tobiasdalhof/sanersocialmedia/assets/59527829/ab5a1e27-1514-4e3a-9a8f-29e9dd6de965">


Kind regards,

Raoul

**Comment by tobiasdalhof** [comment]
PRs are welcome! For a code example, check out the YouTube Shorts site action here: https://github.com/tobiasdalhof/sanersocialmedia/blob/main/packages/core/src/sites/youtube.ts#L68

The technique involves: 

1. Hiding the reels page via `injectCss`, which can be challenging due to Instagram's obscure class names.
2. Muting all audio and video elements.
3. Adding the quote to the page.

**Comment by tobiasdalhof** [comment]
Submitted v1.7.0

![image](https://github.com/tobiasdalhof/sanersocialmedia/assets/10046578/f3647cb6-4c09-4c4d-b48e-df82a90f27ed)
